aspect:
    - HOTEL_ROOM#QUALITY
    - HOTEL_ROOM#PRICES 
    - HOTEL_ROOM#CLEANLINESS
    - HOTEL_ROOM#GENERAL
    - FACILITY#GENERAL
    - FOOD#QUALITY
    - FOOD#OPTION
    - SERVICE#GENERAL 
    - LOCATION#GENERAL
labels: 
    - negative
    - neutral
    - positive
pretrained: vinai/phobert-base-v2
use_lstm: True
num_layers_lstm: 2
word_embedding_dim: 512
num_embeddings: 256
batch_size: 256
num_workers: 2
num_epochs: 30

train_file: data/hotel_absa_train.txt
val_file: data/hotel_absa_val.txt
test_file: data/hotel_absa_test.txt

freeze_embedder: True
acd_warmup: 30
acd_only: False
acsc_only: False
lr: 0.00005
weight_decay: 0.00001
acd_loss_weight: 1.0 
acsc_loss_weight: 1.0
saved_model: log/model_absa.bin
model_save_path: log/model_absa.bin
