aspect:
    - FOOD#PRICES
    - FOOD#QUALITY
    - FOOD#STYLE&OPTIONS
    - DRINKS#PRICES
    - DRINKS#QUALITY
    - DRINKS#STYLE&OPTIONS
    - RESTAURANT#PRICES
    - RESTAURANT#GENERAL
    - RESTAURANT#MISCELLANEOUS
    - SERVICE#GENERAL
    - AMBIENCE#GENERAL
    - LOCATION#GENERAL
labels: 
    - negative
    - neutral
    - positive
pretrained: vinai/phobert-base-v2
use_lstm: True
num_layers_lstm: 2
word_embedding_dim: 512
num_embeddings: 256
batch_size: 256
num_workers: 2
num_epochs: 30

train_file: data/1-VLSP2018-SA-Restaurant-train (7-3-2018).txt
val_file: data/2-VLSP2018-SA-Restaurant-dev (7-3-2018).txt
test_file: data/3-VLSP2018-SA-Restaurant-test (8-3-2018).txt

freeze_embedder: True
acd_warmup: 30
acd_only: False
acsc_only: False
lr: 0.00005
weight_decay: 0.00001
acd_loss_weight: 1.0 
acsc_loss_weight: 1.0
saved_model: log/model_absa.bin
model_save_path: log/model_absa.bin
